### ISSUE TITLE
Could you share the htucker tool from https://www.epfl.ch/labs/anchp/index-html/software/htucker/ with me

### ISSUE THREAD

**Issue by ZpWaitingForSunshine** [akrodger/htucker-matlab-ode#1]
I can't download the tool from https://www.epfl.ch/labs/anchp/index-html/software/htucker/. Could you share me with it. My email is penn0121@163.com. Thank you very much!

**Comment by akrodger** [comment]
It is my decision to leave the distribution of the dependencies of this package with their original authors so as to guarantee the following of any relevant software licenses. Similarly, I would not share an installation of Matlab. Their software may be found at the university server location http://sma.epfl.ch/~anchpcommon/software/htucker/htucker_1.2.zip and I will not be hosting an alternative mirror or emailing any individual users a copy of this.

**Comment by ZpWaitingForSunshine** [comment]
> 



> It is my decision to leave the distribution of the dependencies of this package with their original authors so as to guarantee the following of any relevant software licenses.

Thank you very much!
